### ISSUE TITLE
Cannot copy app.yml

### ISSUE THREAD

**Issue by Sander0542** [sorry-cypress/cy2#1]
When I am running this in GitHub Actions the `app.yml` file does not exist yet. How can I create this file in order to make `cy2` run?

```
Run npx cy2 run --record --key *** --ci-build-id 738732867-20210411170557
node:internal/fs/utils:323
    throw err;
    ^

Error: ENOENT: no such file or directory, copyfile '/home/runner/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/config/app.yml' -> '/home/runner/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/config/_app.yml'
    at Object.copyFileSync (node:fs:2068:3)
    at /home/runner/work/SOPROJ7/SOPROJ7/node_modules/cy2/lib/patch.js:33:10
    at /home/runner/work/SOPROJ7/SOPROJ7/node_modules/npm-which/index.js:35:9
    at /home/runner/work/SOPROJ7/SOPROJ7/node_modules/npm-which/node_modules/which/which.js:87:20
    at /home/runner/work/SOPROJ7/SOPROJ7/node_modules/isexe/index.js:42:5
    at /home/runner/work/SOPROJ7/SOPROJ7/node_modules/isexe/mode.js:8:5
    at FSReqCallback.oncomplete (node:fs:194:5) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/home/runner/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/config/app.yml',
  dest: '/home/runner/.cache/Cypress/7.0.1/Cypress/resources/app/packages/server/config/_app.yml'
}
```

**Comment by agoldis** [comment]
@Sander0542 Hmm interesting... You are saying it doesn't exist "yet"? 
It is expecting cypress to be installed locally and tries to locate `app.yml` automatically.



May be it fails to detect the location correctly. Any chance you can find the actual file location while running the action?

**Comment by Sander0542** [comment]
It turned out cypress did not install automatically during the CI build. I had to run `npx cypress install` first in order to get it working.
