### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by tfrijsewijk** [sorry-cypress/cy2#2]
When using `cy2` on Windows I get an error:

```
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'D:\project\src\lib\tasks\state'
Require stack:
- D:\project\src\node_modules\cy2\lib\patch.js
- D:\project\src\node_modules\cy2\bin\cy2
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at D:\project\src\node_modules\cy2\lib\patch.js:19:19
    at D:\project\src\node_modules\npm-which\index.js:35:9
    at D:\project\src\node_modules\which\which.js:87:20
    at D:\project\src\node_modules\isexe\index.js:42:5
    at D:\project\src\node_modules\isexe\windows.js:36:5
    at FSReqCallback.oncomplete (fs.js:184:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\project\\src\\node_modules\\cy2\\lib\\patch.js',
    'D:\\project\\src\\node_modules\\cy2\\bin\\cy2'
  ]
}
```

**Comment by tfrijsewijk** [comment]
Upon reading the source code I found the answer: no 😅

**Comment by tfrijsewijk** [comment]
So I patched a solution together:

```js
const path = require('path');
const fs = require('fs');
const cp = require('child_process');
const which = require('npm-which')(process.cwd());
const yaml = require('js-yaml');

const DEFAULT_OVERRIDE_URL = 'https://api.cypress.io/';

exports.patch = function () {
  which('cypress', function (err, binaryCypress) {
    if (err) return console.error(err.message);
    const cypressPath = require.resolve('cypress');
    const cypressRoot = path.dirname(cypressPath);
    const stateModulePath = path.resolve(cypressRoot, 'lib/tasks/state');
    const state = require(stateModulePath);

    const pkgPath = state.getBinaryPkgPath(state.getBinaryDir());
    const pkgRoot = path.dirname(pkgPath);
    const configPath = path.resolve(pkgRoot, 'packages/server/config/app.yml')
    const backupConfigFilePath = path.resolve(pkgRoot, 'packages/server/config/_app.yml');

    try {
      fs.statSync(backupConfigFilePath);
    } catch (e) {
      fs.copyFileSync(configPath, backupConfigFilePath);
    }

    const doc = yaml.load(fs.readFileSync(configPath, 'utf8'));
    doc.production.api_url =
      process.env.CYPRESS_API_URL || DEFAULT_OVERRIDE_URL;

    fs.writeFileSync(configPath, yaml.dump(doc));

    const cliBinPath = fs.realpathSync(binaryCypress);
    const [node, script, ...rest] = process.argv;
    cp.spawn(cliBinPath, [...rest], { stdio: 'inherit' });
  });
};
```

I'll try to fork and submit a PR later this weekend.. Don't pin me down on it! 😬

**Comment by tfrijsewijk** [comment]
Thanks for all your great work @agoldis
