### ISSUE TITLE
cannot find module 'node_modules\.bin\node_modules\cypress\lib\tasks\state'

### ISSUE THREAD

**Issue by ajboni** [sorry-cypress/cy2#8]
Hello, I'm having the following issue trying to run it in Windows: seems similar to #2 
```
cannot find module 'C:\dev\QATesting\node_modules\.bin\node_modules\cypress\lib\tasks\state'
Require stack:
- C:\dev\QATesting\node_modules\cy2\lib\patch.js
- C:\dev\QATesting\node_modules\cy2\index.js
- C:\dev\QATesting\node_modules\cy2\bin\cy2
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at getConfigFilesPaths (C:\dev\QATesting\node_modules\cy2\lib\patch.js:56:17)
    at async Object.exports.patch (C:\dev\QATesting\node_modules\cy2\lib\patch.js:11:52)
    at async Object.exports.run (C:\dev\QATesting\node_modules\cy2\index.js:8:3) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\dev\\QATesting\\node_modules\\cy2\\lib\\patch.js',
    'C:\\dev\\QATesting\\node_modules\\cy2\\index.js',
    'C:\\dev\\QATesting\\node_modules\\cy2\\bin\\cy2'
  ]
}
```

**Comment by testingJava2** [comment]
Hello @ajboni,
I have reported the same to Andrew, in issue #4.
Not sure if he will decide to track it there or here, but just for your info.

**Comment by agoldis** [comment]
Trying to resolve, please downgrade to https://www.npmjs.com/package/cy2/v/1.1.0-beta.0 meanwhile

**Comment by ajboni** [comment]
I can confirm it's working here as well! Thank you!!
